apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  generateName: health-api-calculator-latency-
  namespace: nutrition
spec:
  mode: fixed-percent
  value: "50"
  selector:
    labelSelectors:
      app: health-api
    namespaces:
      - nutrition
  target: Request
  port: 8080
  method: POST
  path: /calculator*
  delay: 3s
  duration: 30s